### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by BloatedVirus** [BloatedVirus/make-it-personal#2]

**Comment by benoitboucart** [comment]
Concept is ok, de vraag is natuurlijk hoe je het allemaal (de thee's etc.) zal visualiseren (hoe je de thee samensteller zal maken, welke opties je kan meegeven bij het samenstellen van een thee, hoe die uiteindelijk zal gevisualiseerd worden, etc. Dit is mij nog niet duidelijk.

Denk ook na over welke service(s) of dienst(en) je zal integreren.

Vergeet je in de toekomst ook niet om Simon mee te assignen bij de issues? (en uit te nodigen aan je GitHub project mocht dit nog niet het geval zijn).

Succes!
